### ISSUE TITLE
Windows共有のGuestアクセスと、匿名アクセスの両立方法について

### ISSUE THREAD

**Issue by mikotomaniax** [ComittoNxA/ComittoNxX#2]
https://itest.5ch.net/egg/test/read.cgi/android/1709131473/ の 862 より

Windows共有がGuestアクセスを期待している場合、jcifs認証（FileAccess.jcifFile）でcontextをwithAnonymousCredentialsではなくwithGuestCrendentialsで作成する必要がありました。
その代わり、匿名アクセスを期待するサーバーに接続出来なくなってしまいます。

対応するには設定を追加して匿名とGuestを切り換える必要がありますが、両タイプのサーバーを運用している可能性を考えると、全体の設定よりも各サーバーの設定にそれぞれ持たせた方が汎用的では無いかと考えます。
ただ、サーバーの設定を変更した場合に別バージョンのComittoNx?との間で設定のインポート/エクスポートが機能しなくなる可能性が考えられました。

どの様な方針で対応すれば良いか、こちらで回答いただければと思います。
よろしくお願いします。

**Comment by ComittoNxA** [comment]
アカウント名にguestと書いたらゲストアクセス、何も書かなかったら匿名アクセスとかでどうでしょうか？

**Comment by mikotomaniax** [comment]
回答ありがとうございます。
それは良い案ですね！

影響もFileAccess.jcifFileだけに収まりそうです。
試して見ます。
